sudo: false
language: ruby
dist: bionic
git:
  depth: false
  quiet: true
# Blacklist
branches:
  except:
    - gh-pages
before_install:
  - sudo apt-get install -y doxygen graphviz
script:
   - bundle install
   - bundle exec arduino_ci_remote.rb
   - cd src
   # normal library build
   - make
   # tests build another version of the library (only a static one) and test
   # against it with sanitizers
   - make test

matrix:
  include:
    - compiler: gcc
      os: linux

    - compiler: clang
      os: osx
